server:
  port: 8085
spring:
  application:
    name: OrderService
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
jwt:
  secret: ${JWT_SECRET}
user-service:
  url: http://localhost:8083
  path: /api/v1/users