--liquibase formatted sql

--changeset dshparko:1
insert into items (name, price) values ('Honey Graham Crackers', 3.29);
insert into items (name, price) values ('Electric Butter Churn', 49.99);
insert into items (name, price) values ('Pecan Nuts', 6.49);
insert into items (name, price) values ('Lemon Zest Olive Oil', 8.99);
insert into items (name, price) values ('Popcorn Chicken', 6.49);
insert into items (name, price) values ('Gluten-Free Brownies', 4.99);
insert into items (name, price) values ('Wooden Kitchen Utensil Set', 19.99);
insert into items (name, price) values ('Chipotle Black Bean Burger', 4.99);
insert into items (name, price) values ('Peach Fruit Cups', 1.99);
insert into items (name, price) values ('Wireless Gaming Mouse', 39.99);
insert into items (name, price) values ('Digital Wireless Camera', 199.99);
insert into items (name, price) values ('Savory Oatmeal Cups', 1.99);
insert into items (name, price) values ('Granola', 4.79);
insert into items (name, price) values ('USB Desk Fan', 14.99);
insert into items (name, price) values ('Pet Bed', 39.99);
insert into items (name, price) values ('Children''s Educational Puzzle', 19.99);
insert into items (name, price) values ('Noise-Canceling Headphones', 119.99);
insert into items (name, price) values ('Frozen Cauliflower Rice', 2.99);
insert into items (name, price) values ('Garden Hose', 32.99);
insert into items (name, price) values ('Herb-Infused Olive Oil', 8.99);
insert into items (name, price) values ('Plant Growing Kit', 22.99);
insert into items (name, price) values ('Spiralizer', 22.99);
insert into items (name, price) values ('Cheddar Cheese Crackers', 2.29);
insert into items (name, price) values ('Honey Garlic Chicken', 8.49);
insert into items (name, price) values ('Paint By Numbers Kit', 24.99);
insert into items (name, price) values ('Lentil Soup', 2.49);
insert into items (name, price) values ('Coloring Books for Adults', 14.99);
insert into items (name, price) values ('Ginger Turmeric Latte Mix', 5.29);
insert into items (name, price) values ('Ceramic Knife Set', 39.99);
insert into items (name, price) values ('Over-The-Door Shoe Organizer', 25.99);
insert into items (name, price) values ('Outdoor Fire Pit', 149.99);
insert into items (name, price) values ('Chocolate Hazelnut Spread', 5.99);
insert into items (name, price) values ('Home Brewing Starter Kit', 79.99);
insert into items (name, price) values ('Honey Garlic Shrimp', 8.49);
insert into items (name, price) values ('Microfiber Cleaning Cloth Set', 9.99);
insert into items (name, price) values ('Sriracha Hot Chili Sauce', 2.99);
insert into items (name, price) values ('Jump Rope with Counter', 12.99);
insert into items (name, price) values ('Mini Waffle Maker', 24.99);
insert into items (name, price) values ('Almond Flour Biscuits', 6.49);
insert into items (name, price) values ('Bluetooth Tracker', 19.99);
insert into items (name, price) values ('Whole Wheat Pasta', 2.49);
insert into items (name, price) values ('Face Mask Set', 19.99);
insert into items (name, price) values ('Leather Notebook Cover', 29.99);
insert into items (name, price) values ('Ceramic Planter Set', 39.99);
insert into items (name, price) values ('Almond Joy Snack Bars', 2.99);
insert into items (name, price) values ('Beef Tacos', 5.49);
insert into items (name, price) values ('Teriyaki Chicken Wings', 10.99);
insert into items (name, price) values ('Smashed Avocado with Lime', 2.49);
insert into items (name, price) values ('Self-Adhesive Wallpaper', 34.99);
insert into items (name, price) values ('Basil Pesto Pasta', 6.49);
insert into items (name, price) values ('Cheddar Cheese Slices', 3.49);
insert into items (name, price) values ('Non-Stick Baking Sheet', 18.99);
insert into items (name, price) values ('Travel Size Toiletry Bottles', 9.99);
insert into items (name, price) values ('Honeycrisp Apples', 1.89);
insert into items (name, price) values ('Cilantro Lime Rice', 2.99);
insert into items (name, price) values ('Organic Black Beans', 1.29);
insert into items (name, price) values ('Almond Flour Pizza Crust', 7.99);
insert into items (name, price) values ('BBQ Sauce', 3.49);
insert into items (name, price) values ('Kale and Quinoa Salad', 6.49);
insert into items (name, price) values ('Heavy Duty Gardening Tool Set', 49.99);
insert into items (name, price) values ('Digital Photo Frame', 79.99);
insert into items (name, price) values ('Pet Camera with Treat Dispenser', 149.99);
insert into items (name, price) values ('Natural Fruit Snacks', 3.99);
insert into items (name, price) values ('Digital Kitchen Timer', 14.99);
insert into items (name, price) values ('Grilled Vegetable Medley', 4.49);
insert into items (name, price) values ('Portable Solar Charger', 29.99);
insert into items (name, price) values ('Basic V-Neck T-Shirt', 19.99);
insert into items (name, price) values ('Puffer Winter Coat', 99.99);
insert into items (name, price) values ('Vegan Tacos', 7.49);
insert into items (name, price) values ('Whole Wheat Pasta', 2.49);
insert into items (name, price) values ('Electric Fondue Pot', 39.99);
insert into items (name, price) values ('Savory Pumpkin Soup', 3.89);
insert into items (name, price) values ('Lemon Herb Grilled Chicken', 9.99);
insert into items (name, price) values ('Chocolate Chip Pancake Mix', 3.99);
insert into items (name, price) values ('Reversible Comforter Set', 89.99);
insert into items (name, price) values ('Organic Honeycrisp Apples', 1.99);
insert into items (name, price) values ('Smoky BBQ Jackfruit', 4.99);
insert into items (name, price) values ('Asian Stir-Fry Kit', 5.49);
insert into items (name, price) values ('Cranberry Juice', 3.69);
insert into items (name, price) values ('Vegetarian Pizza', 5.49);
insert into items (name, price) values ('Sweet Corn Fritters', 4.49);
insert into items (name, price) values ('Multi-Function Smartphone Holder', 12.99);
insert into items (name, price) values ('Samoas Cookie Mix', 5.59);
insert into items (name, price) values ('Smart Thermos', 39.99);
insert into items (name, price) values ('Travel Mug', 18.99);
insert into items (name, price) values ('Savory Rice Cakes', 2.5);
insert into items (name, price) values ('Photo Album', 24.99);
insert into items (name, price) values ('Sketchbook', 14.99);
insert into items (name, price) values ('Smart Doorbell', 119.99);
insert into items (name, price) values ('Italian Herbal Seasoning', 1.99);
insert into items (name, price) values ('Spicy Thai Chili Sauce', 3.29);
insert into items (name, price) values ('Fruit and Nut Energy Bites', 2.99);
insert into items (name, price) values ('Wireless Charger', 24.99);
insert into items (name, price) values ('Avocado Lime Dressing', 4.29);
insert into items (name, price) values ('Mango Chunks', 4.89);
insert into items (name, price) values ('Garlic Naan Bread', 3.99);
insert into items (name, price) values ('Multi-Function Meat Tenderizer', 19.99);
insert into items (name, price) values ('Sour Cream', 3.49);
insert into items (name, price) values ('Slim Wallet', 24.99);
insert into items (name, price) values ('Leek and Potato Soup', 3.29);
insert into items (name, price) values ('Kettle Chip Variety Pack', 3.99);
insert into items (name, price) values ('Ice Cube Tray with Lid', 10.99);
insert into items (name, price) values ('Smartphone UV Sanitizer', 39.99);
insert into items (name, price) values ('Rechargeable Laptop Battery Pack', 49.99);
insert into items (name, price) values ('Pesto Pasta Salad', 4.99);
insert into items (name, price) values ('Rice Noodles', 3.49);
insert into items (name, price) values ('Crafting Kit', 29.99);
insert into items (name, price) values ('Walnut Halves', 8.49);
insert into items (name, price) values ('Buffalo Chicken Wraps', 5.99);
insert into items (name, price) values ('Halloween Decoration Set', 29.99);
insert into items (name, price) values ('Fruit and Nut Bars', 1.99);
insert into items (name, price) values ('Car Seat Organizer', 14.99);
insert into items (name, price) values ('Vegetable Stir-Fry Sauce', 3.49);
insert into items (name, price) values ('Lockable Bicycle Chain', 19.99);
insert into items (name, price) values ('Peanut Butter Chocolate Clusters', 2.99);
insert into items (name, price) values ('Colorful Post-It Notes Set', 9.99);
insert into items (name, price) values ('Lemon Zest Olive Oil', 8.99);
insert into items (name, price) values ('Chocolate Dipped Fruit', 5.99);
insert into items (name, price) values ('Smartphone Camera Lens Kit', 19.99);
insert into items (name, price) values ('Adjustable Kitchen Broom Stand', 14.99);
insert into items (name, price) values ('Wireless Earbud Silicone Covers', 9.99);
insert into items (name, price) values ('Fitness Jump Rope', 15.99);
insert into items (name, price) values ('Reversible Comforter Set', 89.99);
insert into items (name, price) values ('Mango Chilli Sauce', 3.99);
insert into items (name, price) values ('Aged White Cheddar Popcorn', 2.99);
insert into items (name, price) values ('Smart Doorbell', 119.99);
insert into items (name, price) values ('Home Brewing Starter Kit', 79.99);
insert into items (name, price) values ('Garlic Butter Shrimp', 8.99);
insert into items (name, price) values ('Compact Folding Table', 49.99);
insert into items (name, price) values ('Spicy Vegetable Sushi Rolls', 8.49);
insert into items (name, price) values ('Photo Album', 24.99);
insert into items (name, price) values ('Lentils', 2.99);
insert into items (name, price) values ('Spicy Thai Coconut Soup', 3.99);
insert into items (name, price) values ('Cinnamon Raisin Bread', 3.79);
insert into items (name, price) values ('Portable SSD', 129.99);
insert into items (name, price) values ('Electric Blanket', 59.99);
insert into items (name, price) values ('Car Sunshade', 19.99);
insert into items (name, price) values ('Frozen Fruit Medley', 5.99);
insert into items (name, price) values ('Mediterranean Chickpea Salad', 5.99);
insert into items (name, price) values ('Body Pillow Case', 14.99);
insert into items (name, price) values ('Kale and Quinoa Salad', 6.49);
insert into items (name, price) values ('Crispy Kale Chips', 2.99);
insert into items (name, price) values ('Vegetable Potstickers', 5.99);
insert into items (name, price) values ('Beard Grooming Kit', 34.99);
insert into items (name, price) values ('Classic Cheesecake Mix', 4.99);
insert into items (name, price) values ('Tailored Dress Pants', 79.99);
insert into items (name, price) values ('Organic Black Rice', 3.59);
insert into items (name, price) values ('Backpack', 49.99);
insert into items (name, price) values ('Sesame Noodles', 5.99);
insert into items (name, price) values ('Cold Brew Coffee Maker', 34.99);
insert into items (name, price) values ('Kids'' Crafting Station', 49.99);
insert into items (name, price) values ('Pet Camera with Treat Dispenser', 149.99);
insert into items (name, price) values ('Silicone Cooking Utensils Set', 34.99);
insert into items (name, price) values ('Ranch Dressing', 2.59);
insert into items (name, price) values ('Herbal Garden Starter Kit', 24.99);
insert into items (name, price) values ('Fashionable Fanny Pack', 24.99);
insert into items (name, price) values ('Mini Waffle Maker', 24.99);
insert into items (name, price) values ('Black Bean Soup', 3.49);
insert into items (name, price) values ('Basketball', 29.99);
insert into items (name, price) values ('Caramelized Onion Dip Mix', 2.29);
insert into items (name, price) values ('Brownie Bites', 4.99);
insert into items (name, price) values ('Mini Indoor Hydroponic Garden', 59.99);
insert into items (name, price) values ('Classic Slim Fit Shirt', 49.99);
insert into items (name, price) values ('Tennis Racket', 89.99);
insert into items (name, price) values ('Travel Yoga Mat', 34.99);
insert into items (name, price) values ('Kids'' Science Experiment Kit', 29.99);
insert into items (name, price) values ('Laptop Stand', 29.99);
insert into items (name, price) values ('Mesh Sports Leggings', 39.99);
insert into items (name, price) values ('Water Bottle', 18.99);
insert into items (name, price) values ('Sweet Pea Hummus', 4.29);
insert into items (name, price) values ('Pumpkin Waffles', 4.49);
insert into items (name, price) values ('Multicolored LED Strip Lights', 29.99);
insert into items (name, price) values ('Plant-Based Cookbook', 29.99);
insert into items (name, price) values ('Pet Travel Bed', 26.99);
insert into items (name, price) values ('Caramel Apple Chips', 3.49);
insert into items (name, price) values ('DIY Lip Balm Making Kit', 22.99);
insert into items (name, price) values ('Rainbow Veggie Chips', 3.29);
insert into items (name, price) values ('Lemon Pepper Seasoning', 3.29);
insert into items (name, price) values ('Cinnamon Roll Kit', 6.89);
insert into items (name, price) values ('Portable Solar Camp Shower', 29.99);
insert into items (name, price) values ('Waffle Maker', 39.99);
insert into items (name, price) values ('Wireless Smart Plug', 19.99);
insert into items (name, price) values ('Smart Scale', 59.99);
insert into items (name, price) values ('Grapes (red)', 3.49);
insert into items (name, price) values ('Travel Hair Straightener', 29.99);
insert into items (name, price) values ('Frozen Broccoli', 2.49);
insert into items (name, price) values ('Smart Wi-Fi Light Bulbs', 19.99);
insert into items (name, price) values ('Freestanding Wine Rack', 79.99);
insert into items (name, price) values ('Protein Powder', 44.99);
insert into items (name, price) values ('Electric Bike', 899.99);
insert into items (name, price) values ('Sourdough Bread', 4.99);
insert into items (name, price) values ('Insulated Lunch Box', 24.99);
insert into items (name, price) values ('Fitness Jump Rope', 15.99);
insert into items (name, price) values ('Herb Seasoned Rice', 2.99);
insert into items (name, price) values ('Travel Jewelry Organizer', 19.99);
insert into items (name, price) values ('Sliced Cucumbers', 1.29);
insert into items (name, price) values ('Chickpeas', 1.29);
insert into items (name, price) values ('Sesame Garlic Noodles', 3.49);
insert into items (name, price) values ('Adjustable Dog Harness', 24.99);
insert into items (name, price) values ('Craft Beer Mustard', 3.99);
insert into items (name, price) values ('High-Speed Hand Blender', 39.99);
insert into items (name, price) values ('Chocolate Fudge Brownie Mix', 2.99);
insert into items (name, price) values ('Fitness Foam Roller', 29.99);
insert into items (name, price) values ('Classic Black Dress', 79.99);
insert into items (name, price) values ('Cauliflower Rice Stir-Fry', 4.99);
insert into items (name, price) values ('Wireless Game Controller', 39.99);
insert into items (name, price) values ('Himalayan Pink Salt', 1.99);
insert into items (name, price) values ('Pear and Gorgonzola Salad', 5.49);
insert into items (name, price) values ('Pet Hair Vacuum Attachment', 14.99);
insert into items (name, price) values ('Electric Griddle', 54.99);
insert into items (name, price) values ('Athletic Jogging Jacket', 49.99);
insert into items (name, price) values ('Chocolate Chip Muffins', 3.99);
insert into items (name, price) values ('Lemon Garlic Marinade', 4.29);
insert into items (name, price) values ('Vegan Mayonnaise', 4.49);
insert into items (name, price) values ('Kettle BBQ Grill', 99.99);
insert into items (name, price) values ('Set of Decorative Storage Bins', 34.99);
insert into items (name, price) values ('Lemon Sorbet', 4.99);
insert into items (name, price) values ('Chickpeas', 1.29);
insert into items (name, price) values ('Tabletop Fire Pit', 79.99);
insert into items (name, price) values ('Chickpea Salad', 5.49);
insert into items (name, price) values ('Smartphone Tripod with Bluetooth Remote', 29.99);
insert into items (name, price) values ('Honey Sesame Cashews', 4.49);
insert into items (name, price) values ('Californian Raisins', 3.19);
insert into items (name, price) values ('Avocado Lime Dressing', 4.29);
insert into items (name, price) values ('Smartphone UV Sanitizer', 39.99);
insert into items (name, price) values ('Peanut Butter Protein Balls', 5.29);
insert into items (name, price) values ('Asian Stir-Fry Vegetables', 2.99);
insert into items (name, price) values ('Collapsible Folding Chair', 29.99);
insert into items (name, price) values ('Cheesy Broccoli Soup Mix', 2.99);
insert into items (name, price) values ('Peach Mango Smoothie Mix', 5.99);
insert into items (name, price) values ('Pistachio Ice Cream', 4.99);
insert into items (name, price) values ('Sushi Roll Kit', 9.99);
insert into items (name, price) values ('Solar Garden Lights', 39.99);
insert into items (name, price) values ('Cinnamon Spiced Almonds', 5.99);
insert into items (name, price) values ('Cranberry Almond Cookies', 4.29);
insert into items (name, price) values ('Garlic Parmesan Roasted Nuts', 4.89);
insert into items (name, price) values ('Peach Slices (canned)', 2.49);
insert into items (name, price) values ('Wireless Charger Stand', 24.99);
insert into items (name, price) values ('Cordless Water Flosser', 49.99);
insert into items (name, price) values ('Smoked Paprika Chicken Thighs', 6.99);
insert into items (name, price) values ('Lemon Garlic Marinade', 4.29);
insert into items (name, price) values ('Smartphone Holder for Car', 14.99);
insert into items (name, price) values ('Kids'' Educational Tablet', 129.99);
insert into items (name, price) values ('Honey Sesame Chicken', 8.99);
insert into items (name, price) values ('Beard Grooming Kit', 34.99);
insert into items (name, price) values ('Smartphone Camera Lens Kit', 19.99);
insert into items (name, price) values ('Yoga Wheel', 34.99);
insert into items (name, price) values ('Almond Joy Munch Bars', 1.39);
insert into items (name, price) values ('Peanut Butter Cookies', 3.49);
insert into items (name, price) values ('Natural Fruit Snacks', 3.99);
insert into items (name, price) values ('Wall Decals for Kids', 24.99);
insert into items (name, price) values ('Smartphone Projector', 29.99);
insert into items (name, price) values ('Almond Butter Cookies', 4.49);
insert into items (name, price) values ('Screen Cleaning Kit', 15.99);
insert into items (name, price) values ('Luxury Memory Foam Mattress Topper', 129.99);
insert into items (name, price) values ('Radish Chips', 2.89);
insert into items (name, price) values ('Memory Foam Pillow', 39.99);
insert into items (name, price) values ('Tactical Backpack', 59.99);
insert into items (name, price) values ('Italian Sausage and Peppers', 8.99);
insert into items (name, price) values ('Zesty Garlic Marinade', 4.49);
insert into items (name, price) values ('Wireless Music Receiver', 19.99);
insert into items (name, price) values ('DIY Candle Kit', 34.99);
insert into items (name, price) values ('Warm Knit Beanie', 19.99);
insert into items (name, price) values ('Organic Honeycrisp Apples', 1.99);
insert into items (name, price) values ('Phone Screen Protector', 12.99);
insert into items (name, price) values ('Garlic Naan Bread', 3.99);
insert into items (name, price) values ('Interchangeable Watch Bands', 24.99);
insert into items (name, price) values ('Mini Electric Kettle', 29.99);
insert into items (name, price) values ('Walnut Halves', 8.49);
insert into items (name, price) values ('Chipotle Black Bean Salad', 3.29);
insert into items (name, price) values ('Red Lentil Pasta', 3.99);
insert into items (name, price) values ('Travel Eye Mask with Ear Plugs', 15.99);
insert into items (name, price) values ('Portable Air Conditioner', 299.99);
insert into items (name, price) values ('Kids'' Art Supplies Kit', 29.99);
insert into items (name, price) values ('Ground Cinnamon', 1.99);
insert into items (name, price) values ('Portable Electric Fan', 24.99);
insert into items (name, price) values ('Classic Black Dress', 79.99);
insert into items (name, price) values ('Lightweight Rain Jacket', 79.99);
insert into items (name, price) values ('Chilli Lime Corn on the Cob', 1.99);
insert into items (name, price) values ('Spaghetti and Meatball Dinner Kit', 7.99);
insert into items (name, price) values ('Ramen Noodle Soup Cups', 1.29);
insert into items (name, price) values ('Sesame Noodles', 5.99);
insert into items (name, price) values ('Repair Tool Set for Home Improvement', 29.99);
insert into items (name, price) values ('Garden Hose', 32.99);
insert into items (name, price) values ('Garlic and Herb Cream Cheese', 3.49);
insert into items (name, price) values ('Chipotle Black Bean Salad', 3.29);
insert into items (name, price) values ('Thai Green Curry Paste', 2.49);
insert into items (name, price) values ('Coconut Milk', 2.49);
insert into items (name, price) values ('Weighted Jump Rope', 15.99);
insert into items (name, price) values ('Herbal Tea Infuser', 9.99);
insert into items (name, price) values ('Frozen Vegetarian Pizza', 6.49);
insert into items (name, price) values ('Portable Massage Table', 199.99);
insert into items (name, price) values ('High-Low Hem Tee', 22.99);
insert into items (name, price) values ('Gardening Fairy Figurines', 14.99);
insert into items (name, price) values ('Quinoa Salad', 5.99);
insert into items (name, price) values ('Maple Cinnamon Almonds', 4.29);
insert into items (name, price) values ('Miso Soup Mix', 3.29);
insert into items (name, price) values ('Pet Carrier Backpack', 39.99);
insert into items (name, price) values ('Harvest Grain Salad', 5.49);
insert into items (name, price) values ('Tandoori Chicken Marinade', 2.49);
insert into items (name, price) values ('Dark Chocolate Covered Raisins', 3.99);
insert into items (name, price) values ('Grass Fed Beef Patties', 9.99);
insert into items (name, price) values ('Buffalo Cauliflower Bites', 6.29);
insert into items (name, price) values ('Garlic Butter Sauce', 3.59);
insert into items (name, price) values ('Zesty Garlic Marinade', 4.49);
insert into items (name, price) values ('Spicy Italian Sausage', 4.99);
insert into items (name, price) values ('Dark Chocolate Tart', 6.29);
insert into items (name, price) values ('Two-Tier Fruit Basket', 29.99);
insert into items (name, price) values ('Sushi Roll Kit', 9.99);
insert into items (name, price) values ('Herb Seasoned Rice', 2.99);
insert into items (name, price) values ('Beef Stroganoff Mix', 5.49);
insert into items (name, price) values ('Barbecue Chicken Pizza', 8.99);
insert into items (name, price) values ('Tea Infuser Bottle', 19.99);
insert into items (name, price) values ('Honey Nut Cheerios', 4.29);
insert into items (name, price) values ('Fitness Resistance Bands', 29.99);
insert into items (name, price) values ('Reversible Comforter Set', 89.99);
insert into items (name, price) values ('Reusable Snack Bags', 14.99);
insert into items (name, price) values ('Sesame Oil', 3.99);
insert into items (name, price) values ('Cheesy Broccoli Soup Mix', 2.99);
insert into items (name, price) values ('Creamy Garlic Dressing', 3.99);
insert into items (name, price) values ('Personal Blender', 39.99);
insert into items (name, price) values ('Electric Heating Pad', 20.99);
insert into items (name, price) values ('Savory Italian Herbs', 2.99);
insert into items (name, price) values ('Decorative Throw Pillows', 29.99);
insert into items (name, price) values ('Organic Green Apples', 1.49);
insert into items (name, price) values ('Organic Italian Seasoning', 2.99);
insert into items (name, price) values ('Mango Chunks', 4.89);
insert into items (name, price) values ('Carrot Sticks', 2.49);
insert into items (name, price) values ('Sous Vide Cooker', 79.99);
insert into items (name, price) values ('Savory Italian Herbs', 2.99);
insert into items (name, price) values ('Lemon Sorbet', 4.99);
insert into items (name, price) values ('Phone Screen Protector', 12.99);
insert into items (name, price) values ('Crispy Onion Rings', 4.29);
insert into items (name, price) values ('Sculpting Kit', 25.99);
insert into items (name, price) values ('Caramelized Onion Dip', 3.99);
insert into items (name, price) values ('Adjustable Standing Desk', 299.99);
insert into items (name, price) values ('Handheld Vacuum', 79.99);
insert into items (name, price) values ('Cold Brew Coffee Maker', 34.99);
insert into items (name, price) values ('Spicy Salsa Verde', 3.49);
insert into items (name, price) values ('Organic Cereal Bars', 4.29);
insert into items (name, price) values ('Savory Rice Cakes', 2.5);
insert into items (name, price) values ('Children''s Garden Tool Set', 22.99);
insert into items (name, price) values ('Classic Slim Fit Shirt', 49.99);
insert into items (name, price) values ('Cilantro Lime Rice', 2.99);
insert into items (name, price) values ('Puzzle 3D Model Kit', 22.99);
insert into items (name, price) values ('Hiking Gaiters', 29.99);
insert into items (name, price) values ('High-Waisted Skirt', 34.99);
insert into items (name, price) values ('Stuffed Peppers with Quinoa', 7.99);
insert into items (name, price) values ('Falafel Mix', 2.79);
insert into items (name, price) values ('Maple Pecan Pancake Mix', 4.99);
insert into items (name, price) values ('Insulated Lunch Box', 24.99);
insert into items (name, price) values ('Personalized Cutting Board', 34.99);
insert into items (name, price) values ('Cabbage', 1.29);
insert into items (name, price) values ('Rice Pilaf Mix', 2.59);
insert into items (name, price) values ('Mediterranean Chickpea Salad', 5.99);
insert into items (name, price) values ('Maple Syrup', 6.99);
insert into items (name, price) values ('Cinnamon Sugar Popcorn', 2.89);
insert into items (name, price) values ('Pet Water Fountain with Filtration', 39.99);
insert into items (name, price) values ('Pineapple Teriyaki Chicken Mix', 6.99);
insert into items (name, price) values ('Hydration Backpack', 39.99);
insert into items (name, price) values ('Baked Mac and Cheese', 5.99);
insert into items (name, price) values ('Coconut Rice', 2.29);
insert into items (name, price) values ('Tandoori Chicken Skewers', 7.99);
insert into items (name, price) values ('Electric Opener for Jars and Bottles', 24.99);
insert into items (name, price) values ('Blackberry Jam', 4.29);
insert into items (name, price) values ('Gardening Gloves with Claws', 24.99);
insert into items (name, price) values ('Organic Italian Seasoning', 2.99);
insert into items (name, price) values ('Insulated Lunch Bag', 24.99);
insert into items (name, price) values ('Bamboo Utensil Holder', 14.99);
insert into items (name, price) values ('Teriyaki Stir-Fry Sauce', 3.49);
insert into items (name, price) values ('Pet Bed', 39.99);
insert into items (name, price) values ('Electric Skillet', 49.99);
insert into items (name, price) values ('Over-the-Door Hooks', 12.99);
insert into items (name, price) values ('Magnetic Puzzle Board', 24.99);
insert into items (name, price) values ('Garlic Herb Marinade', 3.29);
insert into items (name, price) values ('Blender Bottle', 12.99);
insert into items (name, price) values ('Rainbow Veggie Chips', 3.29);
insert into items (name, price) values ('Beet Salad', 3.99);
insert into items (name, price) values ('Quality Chef Apron', 19.99);
insert into items (name, price) values ('Herb Drying Rack', 22.99);
insert into items (name, price) values ('Pest Control Traps', 22.99);
insert into items (name, price) values ('Coconut Cream Pie Yogurt', 1.99);
insert into items (name, price) values ('Sea Salt Tortilla Chips', 2.49);
insert into items (name, price) values ('Breathable Face Mask Set', 14.99);
insert into items (name, price) values ('Asian Stir-Fry Vegetables', 2.99);
insert into items (name, price) values ('Lentil Pasta', 4.99);
insert into items (name, price) values ('Home Brewing Starter Kit', 79.99);
insert into items (name, price) values ('DIY Candle Making Kit', 22.99);
insert into items (name, price) values ('Memory Card', 15.99);
insert into items (name, price) values ('Car Vacuum Cleaner', 39.99);
insert into items (name, price) values ('Acoustic Guitar', 199.99);
insert into items (name, price) values ('Sliced Cheese', 4.49);
insert into items (name, price) values ('Butternut Squash Soup', 3.49);
insert into items (name, price) values ('DIY Candle Kit', 34.99);
insert into items (name, price) values ('Suction Cup Hooks', 9.99);
insert into items (name, price) values ('High-Speed HDMI Cable', 12.99);
insert into items (name, price) values ('Outdoor Adventure Backpack', 59.99);
insert into items (name, price) values ('Coconut Milk Yogurt', 2.99);
insert into items (name, price) values ('Trackpad for Laptop', 49.99);
insert into items (name, price) values ('Blueberry Chia Jam', 4.99);
insert into items (name, price) values ('Zucchini Noodle Pasta', 3.99);
insert into items (name, price) values ('Mini Fondue Set', 34.99);
insert into items (name, price) values ('Personalized Pet ID Tags', 9.99);
insert into items (name, price) values ('Glass Food Containers', 34.99);
insert into items (name, price) values ('Gardening Gloves', 15.99);
insert into items (name, price) values ('Chocolate Coconut Protein Balls', 2.99);
insert into items (name, price) values ('Puzzle Game Set', 34.99);
insert into items (name, price) values ('Portable Camping Shower', 39.99);
insert into items (name, price) values ('Whole Roasted Chicken', 9.99);
insert into items (name, price) values ('Lemon Pepper Seasoning', 3.29);
insert into items (name, price) values ('Ice Cream', 5.99);
insert into items (name, price) values ('Yoga Strap', 12.99);
insert into items (name, price) values ('Vegan Mac & Cheese', 8.99);
insert into items (name, price) values ('Frozen Broccoli', 2.49);
insert into items (name, price) values ('Fleece Throw Blanket', 29.99);
insert into items (name, price) values ('Miso Soup Starter', 2.99);
insert into items (name, price) values ('Raspberry Vanilla Greek Yogurt', 3.49);
insert into items (name, price) values ('Sliced Turkey Breast', 5.49);
insert into items (name, price) values ('Reclining Camping Chair', 49.99);
insert into items (name, price) values ('Tattoo Kit', 99.99);
insert into items (name, price) values ('Zucchini Noodles', 3.99);
insert into items (name, price) values ('Fitness Tracker', 49.99);
insert into items (name, price) values ('Chocolate Covered Pretzels', 3.29);
insert into items (name, price) values ('Smoked Paprika Chicken Thighs', 6.99);
insert into items (name, price) values ('Adjustable Height Standing Desk Converter', 89.99);
insert into items (name, price) values ('Mini Indoor Hydroponic Garden', 59.99);
insert into items (name, price) values ('Self-Watering Planters', 49.99);
insert into items (name, price) values ('Mesh Sports Leggings', 39.99);
insert into items (name, price) values ('Italian Breadsticks', 2.49);
insert into items (name, price) values ('Frozen Berry Blend', 4.99);
insert into items (name, price) values ('Apricot Jam', 4.29);
insert into items (name, price) values ('Car Trash Can', 12.99);
insert into items (name, price) values ('Bock Beer Mustard', 2.29);
insert into items (name, price) values ('Spaghetti Sauce', 2.99);
insert into items (name, price) values ('Fire Roasted Salsa', 2.49);
insert into items (name, price) values ('Natural Peanut Butter', 4.29);
insert into items (name, price) values ('Kale & Quinoa Salad Mix', 4.49);
insert into items (name, price) values ('Tandoori Chicken Skewers', 7.99);
insert into items (name, price) values ('Avocados', 1.5);
insert into items (name, price) values ('Kale Salad with Lemon Dressing', 4.99);
insert into items (name, price) values ('Outdoor String Lights', 24.99);
insert into items (name, price) values ('Crew Neck Sweater', 39.99);
insert into items (name, price) values ('Portable Bluetooth Headphones', 79.99);
insert into items (name, price) values ('Jigsaw Puzzle', 14.99);
insert into items (name, price) values ('Italian Breadsticks', 2.49);
insert into items (name, price) values ('Peach Green Tea', 3.49);
insert into items (name, price) values ('Maple Bacon Popcorn', 3.49);
insert into items (name, price) values ('Peanut Butter Banana Smoothie', 3.99);
insert into items (name, price) values ('Lemon Herb Quinoa', 3.49);
insert into items (name, price) values ('Honey Ginger Tea', 2.99);
insert into items (name, price) values ('Digital Photo Frame', 79.99);
insert into items (name, price) values ('Athletic Compression Tights', 39.99);
insert into items (name, price) values ('Greek Yogurt Parfait', 4.49);
insert into items (name, price) values ('Garden Hose', 32.99);
insert into items (name, price) values ('Salt and Pepper Grinder Set', 19.99);
insert into items (name, price) values ('Wall Decals for Kids', 24.99);
insert into items (name, price) values ('Crew Neck Sweater', 39.99);
insert into items (name, price) values ('Smartphone Projector Kit', 24.99);
insert into items (name, price) values ('Ethical Wool Scarf', 29.99);
insert into items (name, price) values ('Motorcycle Phone Mount', 14.99);
insert into items (name, price) values ('Cilantro Lime Rice', 2.99);
insert into items (name, price) values ('Hot Salsa', 2.29);
insert into items (name, price) values ('Herb Seasoned Couscous', 2.49);
insert into items (name, price) values ('Banana Chips', 1.99);
insert into items (name, price) values ('Mediterranean Chickpea Bowl', 6.49);
insert into items (name, price) values ('Ice Cube Tray with Lid', 10.99);
insert into items (name, price) values ('Magnetic Spice Containers', 24.99);
insert into items (name, price) values ('Athletic Jogging Jacket', 49.99);
insert into items (name, price) values ('Insulated Coffee Mug', 24.99);
insert into items (name, price) values ('Dish Soap Dispenser', 18.99);
insert into items (name, price) values ('Chic Jumpsuit', 89.99);
insert into items (name, price) values ('Electric Heat Pad', 24.99);
insert into items (name, price) values ('Emergency Preparedness Kit', 99.99);
insert into items (name, price) values ('Garlic and Herb Rub', 2.29);
insert into items (name, price) values ('Shredded Cheese', 4.29);
insert into items (name, price) values ('Incense Holder', 14.99);
insert into items (name, price) values ('Compact Pop-Up Tent', 69.99);
insert into items (name, price) values ('Electric Kettle', 39.99);
insert into items (name, price) values ('Glass Water Bottle', 25.99);
insert into items (name, price) values ('Smoked Gouda Cheese', 5.49);
insert into items (name, price) values ('Savory Quinoa Pudding', 2.99);
insert into items (name, price) values ('Pet Waterer with Filtration', 39.99);
insert into items (name, price) values ('Electric Meat Grinder', 89.99);
insert into items (name, price) values ('Magnetic Chess Set', 19.99);
insert into items (name, price) values ('Mini Projector', 169.99);
insert into items (name, price) values ('Scent Diffuser', 34.99);
insert into items (name, price) values ('Fettuccine Alfredo Dinner Kit', 5.49);
insert into items (name, price) values ('Mediterranean Olives', 6.49);
insert into items (name, price) values ('Pasta Maker Machine', 59.99);
insert into items (name, price) values ('Spicy Thai Chili Sauce', 3.29);
insert into items (name, price) values ('Vanilla Pudding Mix', 1.29);
insert into items (name, price) values ('Natural Fruit Snacks', 3.99);
insert into items (name, price) values ('Sculpting Kit', 25.99);
insert into items (name, price) values ('Basketball', 29.99);
insert into items (name, price) values ('Frozen Vegetarian Pizza', 6.49);
insert into items (name, price) values ('Sliced Cheese', 4.49);
insert into items (name, price) values ('Digital Kitchen Timer', 14.99);
insert into items (name, price) values ('Marinara Parmesan Baked Ziti', 8.49);
insert into items (name, price) values ('Portable Hammock Swing', 59.99);
insert into items (name, price) values ('Party Mini Dress', 69.99);
insert into items (name, price) values ('Puzzle', 27.99);
insert into items (name, price) values ('Portable SSD', 129.99);
insert into items (name, price) values ('Roasted Vegetable Medley', 3.99);
insert into items (name, price) values ('Wireless Charging Station', 39.99);
insert into items (name, price) values ('High-Speed HDMI Cable', 12.99);
insert into items (name, price) values ('Brownie Bites', 4.99);
insert into items (name, price) values ('Rainbow Veggie Chips', 3.29);
insert into items (name, price) values ('Cinnamon Raisin Bread', 3.79);
insert into items (name, price) values ('Electrolyte Water Bottle', 34.99);
insert into items (name, price) values ('Adjustable Yoga Mat Strap', 14.99);
insert into items (name, price) values ('Strawberry Banana Smoothie Pack', 4.99);
insert into items (name, price) values ('Nut Mix', 5.99);
insert into items (name, price) values ('Chicken Parmesan Dinner Kit', 14.99);
insert into items (name, price) values ('Utility Cargo Pants', 54.99);
insert into items (name, price) values ('Beef Enchilada Casserole', 8.99);
insert into items (name, price) values ('Feta Cheese', 4.99);
insert into items (name, price) values ('Teriyaki Salmon Fillets', 9.99);
insert into items (name, price) values ('Roasted Garlic Mashed Potatoes', 3.99);
insert into items (name, price) values ('Garlic Naan Bread', 3.99);
insert into items (name, price) values ('Multi-Port USB Hub', 19.99);
insert into items (name, price) values ('Bock Beer Mustard', 2.29);
insert into items (name, price) values ('Multi-Purpose Scissors', 8.99);
insert into items (name, price) values ('Linen Trousers', 44.99);
insert into items (name, price) values ('Flavored Popcorn Mix', 2.99);
insert into items (name, price) values ('Canned Coconut Milk', 1.89);
insert into items (name, price) values ('Creamy Spinach Dip', 5.99);
insert into items (name, price) values ('Pasta (Linguine)', 1.89);
insert into items (name, price) values ('Italian Sausage Links', 5.99);
insert into items (name, price) values ('Portable Bluetooth Headphones', 79.99);
insert into items (name, price) values ('Printed Maxi Skirt', 39.99);
insert into items (name, price) values ('Pasta Portion Control Measure', 9.99);
insert into items (name, price) values ('Sun Protection Clothing', 44.99);
insert into items (name, price) values ('Personal Blender with Cups', 34.99);
insert into items (name, price) values ('Brown Sugar', 1.79);
insert into items (name, price) values ('Honey BBQ Riblets', 12.99);
insert into items (name, price) values ('Nordic Berry Smoothie', 3.99);
insert into items (name, price) values ('Organic Chia Seeds', 7.99);
insert into items (name, price) values ('Pet Nail Clipper', 12.99);
insert into items (name, price) values ('Crispy Tofu Bites', 4.99);
insert into items (name, price) values ('Honey Sesame Cashews', 4.49);
insert into items (name, price) values ('Salt and Pepper Grinder Set', 19.99);
insert into items (name, price) values ('Cotton Basic Tank', 14.99);
insert into items (name, price) values ('Sesame Garlic Stir-Fry Sauce', 2.79);
insert into items (name, price) values ('Tea Infuser', 12.99);
insert into items (name, price) values ('Sunglasses Case', 15.99);
insert into items (name, price) values ('Teriyaki Chicken Wings', 10.99);
insert into items (name, price) values ('Olive Oil', 7.99);
insert into items (name, price) values ('Hand Mixer', 29.99);
insert into items (name, price) values ('Electric Griddle with Removable Plates', 59.99);
insert into items (name, price) values ('Beef Stroganoff Mix', 5.49);
insert into items (name, price) values ('Spicy BBQ Sauce', 3.99);
insert into items (name, price) values ('Lemon Dill Chicken Skewers', 9.99);
insert into items (name, price) values ('Sesame Seeds', 1.99);
insert into items (name, price) values ('Maple Breakfast Sausage', 5.99);
insert into items (name, price) values ('Blue Corn Tortilla Chips', 3.49);
insert into items (name, price) values ('Waterproof Rain Boots', 69.99);
insert into items (name, price) values ('Sesame Noodles', 5.99);
insert into items (name, price) values ('Non-Stick Baking Sheets', 29.99);
insert into items (name, price) values ('Garlic Herb Seasoning', 1.99);
insert into items (name, price) values ('Travel Mug with Leak-Proof Lid', 24.99);
insert into items (name, price) values ('Electric Kettle with Temperature Control', 49.99);
insert into items (name, price) values ('Sesame Seeds', 1.99);
insert into items (name, price) values ('Steak Seasoning Rub', 2.49);
insert into items (name, price) values ('Vegetable Fried Rice', 4.99);
insert into items (name, price) values ('Multi-Port USB Hub', 19.99);
insert into items (name, price) values ('Collapsible Water Bottle', 12.99);
insert into items (name, price) values ('Fresh Basil Pesto', 4.79);
insert into items (name, price) values ('Quinoa', 4.49);
insert into items (name, price) values ('Children''s Musical Instrument Set', 39.99);
insert into items (name, price) values ('Carrot Ginger Soup', 4.29);
insert into items (name, price) values ('Vacuum Sealer Machine', 89.99);
insert into items (name, price) values ('Animal Paw Print Soap Dispenser', 16.99);
insert into items (name, price) values ('Handmade Leather Journal', 39.99);
insert into items (name, price) values ('Sporty Cap', 15.99);
insert into items (name, price) values ('Beach Cover-Up', 29.99);
insert into items (name, price) values ('Chiffon Blouse', 39.99);
insert into items (name, price) values ('Lentil Vegetable Stew', 4.49);
insert into items (name, price) values ('Sunglasses Case', 15.99);
insert into items (name, price) values ('Asian Noodle Salad Kit', 4.99);
insert into items (name, price) values ('Pocket Blanket', 24.99);
insert into items (name, price) values ('Coconut Chips', 3.59);
insert into items (name, price) values ('Coconut Milk Yogurt', 2.99);
insert into items (name, price) values ('Portable Phone Charger', 29.99);
insert into items (name, price) values ('Deep Tissue Massage Gun', 89.99);
insert into items (name, price) values ('Zesty Garlic Marinade', 4.49);
insert into items (name, price) values ('Rustic Wooden Picture Frame', 19.99);
insert into items (name, price) values ('Herbal Tea Infuser', 9.99);
insert into items (name, price) values ('Honey Garlic Chicken', 8.49);
insert into items (name, price) values ('Garlic Butter Sauce', 3.59);
insert into items (name, price) values ('Pet Water Fountain', 39.99);
insert into items (name, price) values ('Poppy Seed Dressing', 3.49);
insert into items (name, price) values ('Red Lentil Pasta', 3.99);
insert into items (name, price) values ('Tea Set with Infuser', 34.99);
insert into items (name, price) values ('Compact Portable Grill', 79.99);
insert into items (name, price) values ('Adjustable Laptop Desk', 59.99);
insert into items (name, price) values ('Coconut Bowls Set', 22.99);
insert into items (name, price) values ('Kids'' Gardening Kit', 24.99);
insert into items (name, price) values ('Pasta Primavera', 4.99);
insert into items (name, price) values ('Artisan Bread', 4.59);
insert into items (name, price) values ('Underwater Camera', 199.99);
insert into items (name, price) values ('Sesame Garlic Noodles', 3.49);
insert into items (name, price) values ('Chocolate Chip Cliff Bars', 2.49);
insert into items (name, price) values ('Classic Baseball Cap', 24.99);
insert into items (name, price) values ('Watercolor Brush Pens', 19.99);
insert into items (name, price) values ('Dried Mango Slices', 3.49);
insert into items (name, price) values ('Travel Document Organizer', 15.99);
insert into items (name, price) values ('Survival Gear Kit', 59.99);
insert into items (name, price) values ('Couscous', 2.49);
insert into items (name, price) values ('Honey Almond Granola Bars', 3.99);
insert into items (name, price) values ('Graphic Hoodie', 49.99);
insert into items (name, price) values ('Instant Camera', 89.99);
insert into items (name, price) values ('Savory Italian Herbs', 2.99);
insert into items (name, price) values ('Travel Mug', 18.99);
insert into items (name, price) values ('Foot Massager Machine', 59.99);
insert into items (name, price) values ('Maple Syrup', 6.99);
insert into items (name, price) values ('Roasted Garlic Aioli', 3.79);
insert into items (name, price) values ('Fitness Tracker Band', 29.99);
insert into items (name, price) values ('Cranberry Almond Cookies', 4.29);
insert into items (name, price) values ('Portable Laptop Table', 39.99);
insert into items (name, price) values ('Vegetable Stir Fry Mix', 3.29);
insert into items (name, price) values ('Chicken Broth', 2.49);
insert into items (name, price) values ('Crispy Chickpeas', 2.99);
insert into items (name, price) values ('Action Camera', 199.99);
insert into items (name, price) values ('Robot Vacuum Cleaner', 299.99);
insert into items (name, price) values ('Camping Tent', 79.99);
insert into items (name, price) values ('Bluetooth Tracker', 19.99);
insert into items (name, price) values ('Handmade Leather Journal', 39.99);
insert into items (name, price) values ('Tabletop Fire Pit', 79.99);
insert into items (name, price) values ('Marinara Parmesan Baked Ziti', 8.49);
insert into items (name, price) values ('Honey Roasted Peanuts', 3.19);
insert into items (name, price) values ('Classic White T-Shirt', 19.99);
insert into items (name, price) values ('Pork Chops', 9.49);
insert into items (name, price) values ('Classic Caesar Dressing', 3.49);
insert into items (name, price) values ('Motorcycle Phone Mount', 14.99);
insert into items (name, price) values ('Aged White Cheddar Popcorn', 2.99);
insert into items (name, price) values ('Leather Crossbody Bag', 89.99);
insert into items (name, price) values ('Basil-infused Olive Oil', 6.99);
insert into items (name, price) values ('Silicone Stretch Lids', 14.99);
insert into items (name, price) values ('Chickpea Pancakes', 4.99);
insert into items (name, price) values ('Savory Oatmeal Cups', 1.99);
insert into items (name, price) values ('Sliced Bell Peppers', 3.99);
insert into items (name, price) values ('Electric Heat Pad', 24.99);
insert into items (name, price) values ('Kids'' STEM Robotics Kit', 59.99);
insert into items (name, price) values ('Multi-Functional Rice Cooker', 49.99);
insert into items (name, price) values ('Whole Grain Hamburger Buns', 2.69);
insert into items (name, price) values ('Herbal Garden Starter Kit', 24.99);
insert into items (name, price) values ('Outdoor Folding Table', 39.99);
insert into items (name, price) values ('Adjustable Stand for Tablets and Smartphones', 19.99);
insert into items (name, price) values ('Personal Blender with Travel Lid', 34.99);
insert into items (name, price) values ('Wireless Keyboard and Mouse Combo', 34.99);
insert into items (name, price) values ('Smart Thermostat with Wi-Fi', 169.99);
insert into items (name, price) values ('Smartphone Photography Tripod', 29.99);
insert into items (name, price) values ('Himalayan Salt Grinder', 4.99);
insert into items (name, price) values ('Photo Album', 24.99);
insert into items (name, price) values ('Garlic Butter Sauce', 3.59);
insert into items (name, price) values ('Digital Camera', 299.99);
insert into items (name, price) values ('Cranberry Lime Sparkling Water', 1.5);
insert into items (name, price) values ('Buffalo Cauliflower Wings', 6.99);
insert into items (name, price) values ('Organic Cucumber', 1.29);
insert into items (name, price) values ('Fitness Resistance Bands Kit', 29.99);
insert into items (name, price) values ('Cauliflower Gnocchi', 3.59);
insert into items (name, price) values ('Grilled Veggie Burgers', 6.29);
insert into items (name, price) values ('Elegant Maxi Skirt', 44.99);
insert into items (name, price) values ('Essential Oils Diffuser Necklace', 19.99);
insert into items (name, price) values ('Black Bean & Corn Salad', 3.99);
insert into items (name, price) values ('LED Disco Ball Light', 19.99);
insert into items (name, price) values ('Knitted Infinity Scarf', 29.99);
insert into items (name, price) values ('Fire Roasted Salsa', 2.49);
insert into items (name, price) values ('Folding Table', 59.99);
insert into items (name, price) values ('Vanilla Bean Greek Yogurt', 1.99);
insert into items (name, price) values ('Tea Infuser Bottle', 19.99);
insert into items (name, price) values ('LED Strip Lights', 19.99);
insert into items (name, price) values ('Cat Scratching Post with Toys', 44.99);
insert into items (name, price) values ('Personal Blender', 39.99);
insert into items (name, price) values ('Herbal Garden Starter Kit', 24.99);
insert into items (name, price) values ('Honey Garlic Chicken', 8.49);
insert into items (name, price) values ('Electric Rice Cooker with Steamer', 49.99);
insert into items (name, price) values ('Pumpkin Spice Muffins', 3.99);
insert into items (name, price) values ('Gaming Mousepad', 19.99);
insert into items (name, price) values ('Baked Falafel', 5.49);
insert into items (name, price) values ('Warm Knit Beanie', 19.99);
insert into items (name, price) values ('Chocolate Fudge Ice Cream', 5.99);
insert into items (name, price) values ('Elegant Maxi Skirt', 44.99);
insert into items (name, price) values ('Mini Air Hockey Table', 39.99);
insert into items (name, price) values ('Digital Stopwatch Timer', 12.99);
insert into items (name, price) values ('Pine Nuts', 7.99);
insert into items (name, price) values ('Vegetable Pizza Rolls', 6.49);
insert into items (name, price) values ('Cranberry Orange Oatmeal', 2.49);
insert into items (name, price) values ('Sliced Ham', 5.49);
insert into items (name, price) values ('Garlic Herb Seasoning', 1.99);
insert into items (name, price) values ('Reusable Coffee Filter', 10.99);
insert into items (name, price) values ('Sushi Rice', 3.99);
insert into items (name, price) values ('Hair Dryer', 39.99);
insert into items (name, price) values ('Lemon Herb Chicken', 7.49);
insert into items (name, price) values ('Self-Cleaning Cat Litter Box', 199.99);
insert into items (name, price) values ('Adjustable Laptop Desk', 59.99);
insert into items (name, price) values ('Chili Con Carne Mix', 2.99);
insert into items (name, price) values ('Fashionable Scarves Set', 24.99);
insert into items (name, price) values ('Car Emergency Kit', 49.99);
insert into items (name, price) values ('Cordless Water Flosser', 49.99);
insert into items (name, price) values ('Feta Cheese', 4.99);
insert into items (name, price) values ('Crispy Chickpeas', 2.99);
insert into items (name, price) values ('Sesame Garlic Stir-Fry Sauce', 2.79);
insert into items (name, price) values ('Pecan Pie Filling', 3.99);
insert into items (name, price) values ('Ground Cinnamon', 1.99);
insert into items (name, price) values ('Puffer Winter Coat', 99.99);
insert into items (name, price) values ('Peach Mango Smoothie Mix', 5.99);
insert into items (name, price) values ('Apple Sauce', 2.19);
insert into items (name, price) values ('Chicken Salad Kit', 5.99);
insert into items (name, price) values ('Kids'' Art Supplies Kit', 29.99);
insert into items (name, price) values ('Vegetable Korma', 6.49);
insert into items (name, price) values ('Vegan Taco Seasoning', 2.49);
insert into items (name, price) values ('Breathable Face Mask Set', 14.99);
insert into items (name, price) values ('Pet Grooming Scissors', 16.99);
insert into items (name, price) values ('Cat Scratching Post with Toys', 44.99);
insert into items (name, price) values ('Walnut Halves', 8.49);
insert into items (name, price) values ('Honey Mustard Sauce', 3.29);
insert into items (name, price) values ('Summer Tank Dress', 39.99);
insert into items (name, price) values ('Pear and Gorgonzola Salad', 5.49);
insert into items (name, price) values ('Fitness Tracker Band', 29.99);
insert into items (name, price) values ('Travel Sewing Kit', 12.99);
insert into items (name, price) values ('Tomato Paste', 1.29);
insert into items (name, price) values ('Shredded Cheese', 4.29);
insert into items (name, price) values ('Vegetable Fried Rice Mix', 3.99);
insert into items (name, price) values ('Classic Beef Chili', 7.99);
insert into items (name, price) values ('Flavored Instant Oatmeal', 2.99);
insert into items (name, price) values ('Tomato Basil Soup', 3.49);
insert into items (name, price) values ('Coconut Granola', 4.19);
insert into items (name, price) values ('Magnetic Puzzle Board', 24.99);
insert into items (name, price) values ('Organic Honeycrisp Apples', 1.99);
insert into items (name, price) values ('Cheesy Cauliflower Bake', 5.49);
insert into items (name, price) values ('Marinated Artichokes', 3.79);
insert into items (name, price) values ('Heavy Duty Gardening Tool Set', 49.99);
insert into items (name, price) values ('Gardening Tools Set', 45);
insert into items (name, price) values ('Organic Ramen Noodles', 2.89);
insert into items (name, price) values ('Smart Thermostat', 149.99);
insert into items (name, price) values ('Instant Read Meat Thermometer', 24.99);
insert into items (name, price) values ('Chia Seed Pudding Mix', 4.19);
insert into items (name, price) values ('Raspberry Limeade', 1.99);
insert into items (name, price) values ('Spinach and Feta Stuffed Chicken Breast', 8.99);
insert into items (name, price) values ('Pet Grooming Kit', 39.99);
insert into items (name, price) values ('Window Blinds', 59.99);
insert into items (name, price) values ('Tomato Sauce', 2.79);
insert into items (name, price) values ('Red Lentils', 1.99);
insert into items (name, price) values ('Pet Bed with Removable Cover', 49.99);
insert into items (name, price) values ('Self-Massaging Pillow', 49.99);
insert into items (name, price) values ('Adjustable Yoga Mat Strap', 14.99);
insert into items (name, price) values ('Self-Stirring Mug', 19.99);
insert into items (name, price) values ('Portable Blender', 30);
insert into items (name, price) values ('Fitness Smartwatch', 99.99);
insert into items (name, price) values ('Cacao Powder', 4.49);
insert into items (name, price) values ('Organic Italian Seasoning', 2.99);
insert into items (name, price) values ('Creamy Avocado Dip', 3.49);
insert into items (name, price) values ('Indoor Plants', 19.99);
insert into items (name, price) values ('Trainers with Mesh Inserts', 69.99);
insert into items (name, price) values ('Kids'' Art Supplies Kit', 29.99);
insert into items (name, price) values ('Noise Reduction Headphones', 39.99);
insert into items (name, price) values ('Smartphone Hand Grip', 9.99);
insert into items (name, price) values ('Almond Joy Protein Bars', 1.99);
insert into items (name, price) values ('Tea Infuser Bottle', 19.99);
insert into items (name, price) values ('Pear and Gorgonzola Salad', 5.49);
insert into items (name, price) values ('Buffalo Stilton Cheese', 8.99);
insert into items (name, price) values ('Vegetable Stock', 2.49);
insert into items (name, price) values ('Gluten-Free Brownies', 4.99);
insert into items (name, price) values ('Marinated Artichokes', 3.79);
insert into items (name, price) values ('Pine Nuts', 7.99);
insert into items (name, price) values ('Blue Denim Jeans', 49.99);
insert into items (name, price) values ('Magnetic Chess Set', 19.99);
insert into items (name, price) values ('Wireless Smart Plug', 19.99);
insert into items (name, price) values ('Solar Power Bank', 39.99);
insert into items (name, price) values ('Laptop Stand', 29.99);
insert into items (name, price) values ('Roasted Garlic', 4.29);
insert into items (name, price) values ('Savory Oatmeal Cups', 1.99);
insert into items (name, price) values ('Zesty Cilantro Lime Dressing', 3.29);
insert into items (name, price) values ('DIY Organic Gardening Kit', 39.99);
insert into items (name, price) values ('Adjustable Window Blind', 49.99);
insert into items (name, price) values ('Hand Crank Blender', 18.99);
insert into items (name, price) values ('Portable Phone Mug Holder', 14.99);
insert into items (name, price) values ('Lentil Vegetable Curry', 4.49);
insert into items (name, price) values ('Maple Syrup', 6.99);
insert into items (name, price) values ('Thai Peanut Dressing', 3.29);
insert into items (name, price) values ('Sweet Potato Fries', 3.99);
insert into items (name, price) values ('Tomato Sauce', 2.79);
insert into items (name, price) values ('Faux Fur Coat', 129.99);
insert into items (name, price) values ('Inflatable Party Cooler', 19.99);
insert into items (name, price) values ('Avocados', 1.5);
insert into items (name, price) values ('Vegan Alfredo Sauce', 4.99);
insert into items (name, price) values ('Chocolate Chip Cliff Bars', 2.49);
insert into items (name, price) values ('Beach Cover-Up', 29.99);
insert into items (name, price) values ('Granola Bars', 4.99);
insert into items (name, price) values ('Tuscan Bean Soup', 2.49);
insert into items (name, price) values ('Breezy Off-The-Shoulder Top', 34.99);
insert into items (name, price) values ('Digital Photo Frame', 79.99);
insert into items (name, price) values ('Wall-Mounted Wine Rack', 39.99);
insert into items (name, price) values ('Chocolate Coconut Granola', 3.79);
insert into items (name, price) values ('Electric Hot Water Dispenser', 59.99);
insert into items (name, price) values ('Mediterranean Flatbread', 3.5);
insert into items (name, price) values ('Children''s Garden Tool Set', 22.99);
insert into items (name, price) values ('Bamboo Cutting Board Set', 34.99);
insert into items (name, price) values ('Portable Hand Warmer', 24.99);
insert into items (name, price) values ('Low-Fat Cottage Cheese', 2.99);
insert into items (name, price) values ('Zesty Garlic Marinade', 4.49);
insert into items (name, price) values ('Electric Wax Warmer', 22.99);
insert into items (name, price) values ('Scent Diffuser', 34.99);
insert into items (name, price) values ('Set of Measuring Spoons', 12.99);
insert into items (name, price) values ('Portable Projector', 199.99);
insert into items (name, price) values ('Sushi Rice', 3.99);
insert into items (name, price) values ('Vegan chocolate chip cookies', 4.79);
insert into items (name, price) values ('Raspberry Vanilla Greek Yogurt', 3.49);
insert into items (name, price) values ('Artisan Bread', 4.59);
insert into items (name, price) values ('Smartphone Photography Tripod', 29.99);
insert into items (name, price) values ('Almond Butter Cookies', 4.49);
insert into items (name, price) values ('Adjustable Bar Stools', 149.99);
insert into items (name, price) values ('Smart Plug', 19.99);
insert into items (name, price) values ('Balsamic Salad Dressing', 2.99);
insert into items (name, price) values ('Sliced Olives', 1.99);
insert into items (name, price) values ('Bamboo Toothbrush Holder', 14.99);
insert into items (name, price) values ('Reusable Food Storage Bags', 19.99);
insert into items (name, price) values ('Chocolate Mint Protein Shake', 3.99);
insert into items (name, price) values ('Whole Grain Mustard', 3.49);
insert into items (name, price) values ('Savory Oats', 2.49);
insert into items (name, price) values ('Oven-Baked Parmesan Zucchini', 4.99);
insert into items (name, price) values ('Chocolate Syrup', 2.99);
insert into items (name, price) values ('Ginger Tea', 4.99);
insert into items (name, price) values ('Creamy Avocado Dip', 3.49);
insert into items (name, price) values ('Breezy Off-The-Shoulder Top', 34.99);
insert into items (name, price) values ('Lockable Bicycle Chain', 19.99);
insert into items (name, price) values ('Crew Neck Sweater', 39.99);
insert into items (name, price) values ('Digital Wireless Meat Thermometer', 39.99);
insert into items (name, price) values ('Chocolate Dipped Fruit', 5.99);
insert into items (name, price) values ('Kale Caesar Salad Kit', 5.99);
insert into items (name, price) values ('Winter Knit Beanie', 14.99);
insert into items (name, price) values ('Hiking Boots', 79.99);
insert into items (name, price) values ('Over-Ear Headphones', 59.99);
insert into items (name, price) values ('Thai Green Curry Paste', 2.49);
insert into items (name, price) values ('Thai Green Curry Paste', 2.49);
insert into items (name, price) values ('Electric Pressure Washer', 199.99);
insert into items (name, price) values ('Portable Jump Starter', 59.99);
insert into items (name, price) values ('Portable Water Filter', 29.99);
insert into items (name, price) values ('Chocolate Mint Protein Shake', 3.99);
insert into items (name, price) values ('Homestyle Chicken Noodle Soup', 2.99);
insert into items (name, price) values ('Pet Grooming Glove', 12.99);
insert into items (name, price) values ('Magnetic Spice Containers', 24.99);
insert into items (name, price) values ('Garlic and Herb Rub', 2.29);
insert into items (name, price) values ('Herbal Tea Sampler Box', 29.99);
insert into items (name, price) values ('Coconut Macaroons', 4.99);
insert into items (name, price) values ('Chili Beans in Sauce', 1.79);
insert into items (name, price) values ('Classic Leather Wallet', 34.99);
insert into items (name, price) values ('Window Blinds', 59.99);
insert into items (name, price) values ('Fitness Tracker Watch', 79.99);
insert into items (name, price) values ('Frozen Chicken Nuggets', 4.49);
insert into items (name, price) values ('Cranberry Almond Cookies', 4.29);
insert into items (name, price) values ('Wall-Mounted Organizer', 34.99);
insert into items (name, price) values ('Wooden Puzzle Game', 14.99);
insert into items (name, price) values ('Portable Campfire', 39.99);
insert into items (name, price) values ('Window Bird Feeder', 19.99);
insert into items (name, price) values ('Fruit Infuser Water Bottle', 15.99);
insert into items (name, price) values ('Cauliflower Rice Stir-Fry', 4.99);
insert into items (name, price) values ('Caramel Sauce', 3.49);
insert into items (name, price) values ('Chocolate Dipped Fruit', 5.99);
insert into items (name, price) values ('Basmati Rice', 5.79);
insert into items (name, price) values ('Collapsible Storage Crates', 18.99);
insert into items (name, price) values ('Himalayan Pink Salt', 1.99);
insert into items (name, price) values ('Compressed Towel Tablets', 12.99);
insert into items (name, price) values ('Vegetable Medley', 2.99);
insert into items (name, price) values ('Recipe Book Stand', 22.99);
insert into items (name, price) values ('Bock Beer Mustard', 2.29);
insert into items (name, price) values ('Pet Reflective Vest', 18.99);
insert into items (name, price) values ('Pumpkin Pancake Mix', 4.19);
insert into items (name, price) values ('Grilled Veggie Burgers', 6.29);
insert into items (name, price) values ('Weighted Jump Rope', 15.99);
insert into items (name, price) values ('Skincare Fridge', 39.99);
insert into items (name, price) values ('Pet Grooming Kit', 39.99);
insert into items (name, price) values ('Organic Coconut Yogurt', 4.49);
insert into items (name, price) values ('Fitness Mat', 49.99);
insert into items (name, price) values ('Brown Rice', 1.79);
insert into items (name, price) values ('Smart Home Hub', 99.99);
insert into items (name, price) values ('Solar Charger', 39.99);
insert into items (name, price) values ('Brown Sugar', 1.79);
insert into items (name, price) values ('Cinnamon Raisin Bagels', 4.19);
insert into items (name, price) values ('Outdoor Adventure Kit', 89.99);
insert into items (name, price) values ('Ethically-Sourced Coffee Beans', 9.99);
insert into items (name, price) values ('Peach Halves (canned)', 2.49);
insert into items (name, price) values ('USB Flash Drive', 9.99);
insert into items (name, price) values ('Cranberry Almond Cookies', 4.29);
insert into items (name, price) values ('Travel Organizer', 22.99);
insert into items (name, price) values ('Tea Set with Infuser', 34.99);
insert into items (name, price) values ('Outdoor Folding Table', 39.99);
insert into items (name, price) values ('Smart Air Purifier', 199.99);
insert into items (name, price) values ('Zucchini Noodle Pasta', 3.99);
insert into items (name, price) values ('Inspirational Wall Art', 24.99);
insert into items (name, price) values ('Reversible Comforter Set', 89.99);
insert into items (name, price) values ('Herbal Tea Set', 19.99);
insert into items (name, price) values ('Kale Chips', 3.99);
insert into items (name, price) values ('Balsamic Glaze', 4.79);
insert into items (name, price) values ('Emergency Preparedness Kit', 99.99);
insert into items (name, price) values ('Coconut Chips', 3.59);
insert into items (name, price) values ('Ranch Dressing', 2.59);
insert into items (name, price) values ('Smart LED Light Strip', 29.99);
insert into items (name, price) values ('Frozen Pizza', 7.99);
insert into items (name, price) values ('Pepper Jack Cheese Sticks', 2.49);
insert into items (name, price) values ('Herbal Tea Set', 19.99);
insert into items (name, price) values ('Comfort Flats', 44.99);
insert into items (name, price) values ('Cheesy Broccoli Soup Mix', 2.99);
insert into items (name, price) values ('Cheddar Cheese Crackers', 2.29);
insert into items (name, price) values ('Electric Kettle', 39.99);
insert into items (name, price) values ('Guitar Tuner', 19.99);
insert into items (name, price) values ('Whipped Cream Cheese', 2.99);
insert into items (name, price) values ('Luminous Night Light', 15.99);
insert into items (name, price) values ('Spicy Chicken Wings', 9.99);
insert into items (name, price) values ('Maple Almond Yogurt', 1.89);
insert into items (name, price) values ('Herbal Tea Sampler Box', 29.99);
insert into items (name, price) values ('Honey Ginger Tea', 2.99);
insert into items (name, price) values ('Organic Quinoa Chips', 3.99);
insert into items (name, price) values ('Potting Soil', 15.99);
insert into items (name, price) values ('Vegetable Sushi Rolls', 5.99);
insert into items (name, price) values ('Zesty Garlic Hummus', 3.99);
insert into items (name, price) values ('Luxury Bath Robe', 49.99);
insert into items (name, price) values ('Electric Griddle with Lid', 49.99);
insert into items (name, price) values ('Classic Baseball Cap', 24.99);
insert into items (name, price) values ('Wooden Kitchen Utensil Set', 19.99);
insert into items (name, price) values ('Scented Candles', 19.99);
insert into items (name, price) values ('Yoga Mat', 25);
insert into items (name, price) values ('Garlic Herb Cream Cheese', 2.99);
insert into items (name, price) values ('Golf Putting Green', 79.99);
insert into items (name, price) values ('Interactive Robot Toy', 34.99);
insert into items (name, price) values ('Stainless Steel Travel Mug', 19.99);
insert into items (name, price) values ('Collapsible Colander', 14.99);
insert into items (name, price) values ('Dog Training Whistle', 8.99);
insert into items (name, price) values ('Vegetable Potstickers', 5.99);
insert into items (name, price) values ('Travel Pillow', 22.99);
insert into items (name, price) values ('Apricot Jam', 4.29);
insert into items (name, price) values ('Chiffon Blouse', 39.99);
insert into items (name, price) values ('Zucchini Noodles', 3.99);
insert into items (name, price) values ('Avocado Oil', 8.49);
insert into items (name, price) values ('Berries Medley', 6.99);
insert into items (name, price) values ('Couscous Mix', 2.49);
insert into items (name, price) values ('Spiced Pumpkin Soup', 3.99);
insert into items (name, price) values ('Deluxe First Aid Kit', 39.99);
insert into items (name, price) values ('Compact Shoe Rack', 34.99);
insert into items (name, price) values ('Travel Yoga Mat', 34.99);
insert into items (name, price) values ('Skincare Set', 54.99);
insert into items (name, price) values ('Almond Flour Pancake Mix', 5.99);
insert into items (name, price) values ('Granola Bars', 4.99);
insert into items (name, price) values ('Key Finder', 19.99);
insert into items (name, price) values ('Smartphone Photography Tripod', 29.99);
insert into items (name, price) values ('Coconut Milk Yogurt', 2.99);
insert into items (name, price) values ('Wireless Gaming Mouse', 39.99);
insert into items (name, price) values ('Vegetable Pizza Rolls', 6.49);
insert into items (name, price) values ('Herb Garden Planter Box', 49.99);
insert into items (name, price) values ('Screen Cleaning Kit', 15.99);
insert into items (name, price) values ('Tuscan Bean Soup', 2.49);
insert into items (name, price) values ('Lockable Bicycle Chain', 19.99);
insert into items (name, price) values ('Honey Roasted Peanuts', 3.19);
insert into items (name, price) values ('Balsamic Salad Dressing', 2.99);
insert into items (name, price) values ('Organic Ramen Noodles', 2.89);
insert into items (name, price) values ('Peach Mango Smoothie Mix', 5.99);
insert into items (name, price) values ('Trail Mix (Deluxe)', 4.59);
insert into items (name, price) values ('Apple Cinnamon Granola', 4.49);
insert into items (name, price) values ('Almond Coconut Granola', 3.99);
insert into items (name, price) values ('Eco-Friendly Yoga Blocks', 15.99);
insert into items (name, price) values ('Pesto Pasta Sauce', 3.99);
insert into items (name, price) values ('Almond Flour Pancake Mix', 5.99);
insert into items (name, price) values ('Waterproof Rain Boots', 69.99);
insert into items (name, price) values ('Halloween Decoration Set', 29.99);
insert into items (name, price) values ('Pet First Aid Kit', 29.99);
insert into items (name, price) values ('Coffee Capsule Dispenser', 24.99);
insert into items (name, price) values ('Pepper Jack Cheese Slices', 3.49);
insert into items (name, price) values ('Chili Beans (canned)', 1.69);
insert into items (name, price) values ('Indian Curry Sauce', 3.69);
insert into items (name, price) values ('Coconut Cream', 2.99);
insert into items (name, price) values ('Maple Pecan Oatmeal Cookies', 3.99);
insert into items (name, price) values ('Slim Fit Chinos', 54.99);
insert into items (name, price) values ('Glass Tea Pot', 34.99);
insert into items (name, price) values ('Gingerbread House Kit', 6.99);
insert into items (name, price) values ('Garlic Herb Grilled Chicken', 8.99);
insert into items (name, price) values ('Gardening Gloves', 15.99);
insert into items (name, price) values ('Video Camera', 199);
insert into items (name, price) values ('Mini Waffle Maker', 24.99);
insert into items (name, price) values ('Chicken Salad Kit', 5.99);
insert into items (name, price) values ('Mixed Nuts', 5.99);
insert into items (name, price) values ('Golf Polo Shirt', 39.99);
insert into items (name, price) values ('Rice Pilaf Mix', 2.59);
insert into items (name, price) values ('Fashionable Scarves Set', 24.99);
insert into items (name, price) values ('Black Bean Soup', 3.49);
insert into items (name, price) values ('Fried Rice', 4.29);
insert into items (name, price) values ('Travel Mug', 18.99);
insert into items (name, price) values ('Sporty Leggings', 39.99);
insert into items (name, price) values ('Almond Flour Pancake Mix', 5.99);
insert into items (name, price) values ('Cocktail Shaker Set', 29.99);
insert into items (name, price) values ('Mediterranean Olives', 6.49);
insert into items (name, price) values ('Savory Breakfast Sausage', 6.49);
insert into items (name, price) values ('Electric Wax Warmer', 22.99);
insert into items (name, price) values ('Pumpkin Pie Spice', 2.99);
insert into items (name, price) values ('Pet Travel Bowl', 10.99);
insert into items (name, price) values ('Frozen Chicken Nuggets', 4.49);
insert into items (name, price) values ('Puff Pastry', 5.49);
insert into items (name, price) values ('Classic Bagels', 2.99);
insert into items (name, price) values ('Wall-Mounted Bookshelf', 39.99);
insert into items (name, price) values ('Comfortable Jogger Pants', 29.99);
